services:
  j-tech-blog:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - type: volume
        source: j-tech-blog-node_modules
        target: /usr/src/app/node_modules
    command: ["npm", "run", "dev"]
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
volumes:
  j-tech-blog-node_modules:
    driver: local
    name: j-tech-blog-node_modules