services:
  j-tech-blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - type: volume
        source: j-tech-blog-node_modules
        target: /usr/src/app/node_modules
    command:
      - "sh"
      - "-c"
      - |
        npm run dev
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
volumes:
  j-tech-blog-node_modules:
    driver: local
    name: j-tech-blog-node_modules